// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWkoxPzccGWCkqCq1xETk9yNpOg6FdOLg',
    appId: '1:502100720377:web:988e5704d9b398c4ca4028',
    messagingSenderId: '502100720377',
    projectId: 'tondobf-app',
    authDomain: 'tondobf-app.firebaseapp.com',
    storageBucket: 'tondobf-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACkLvcoYFSqKGE-pJ6UtqazAfqbW-jWA',
    appId: '1:502100720377:android:2f5334fbd5c0d080ca4028',
    messagingSenderId: '502100720377',
    projectId: 'tondobf-app',
    storageBucket: 'tondobf-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtx0Eh0ESTqUCCYJ1wr5Ep9ydAOwKqhtE',
    appId: '1:502100720377:ios:4ff9342673e39e09ca4028',
    messagingSenderId: '502100720377',
    projectId: 'tondobf-app',
    storageBucket: 'tondobf-app.firebasestorage.app',
    iosBundleId: 'com.tondo.tondo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtx0Eh0ESTqUCCYJ1wr5Ep9ydAOwKqhtE',
    appId: '1:502100720377:ios:4ff9342673e39e09ca4028',
    messagingSenderId: '502100720377',
    projectId: 'tondobf-app',
    storageBucket: 'tondobf-app.firebasestorage.app',
    iosBundleId: 'com.tondo.tondo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWkoxPzccGWCkqCq1xETk9yNpOg6FdOLg',
    appId: '1:502100720377:web:8229f5b62b615db4ca4028',
    messagingSenderId: '502100720377',
    projectId: 'tondobf-app',
    authDomain: 'tondobf-app.firebaseapp.com',
    storageBucket: 'tondobf-app.firebasestorage.app',
  );
}
